print('Hola, Soy Mariana :)')
print('Hola! Yo soy Anne Bonnie')
print('Linea desde Test_2')
print('Linea de prueba')
print("hola")
print("test")
print("test-udg")
print('Quite los espacios')

print('Prueba 08/05 desde casita')